import { addTypeTemplate } from '@nuxt/kit'

const typesPath = '@mdream/nuxt/runtime/types'

export function registerTypeTemplates() {
  addTypeTemplate({
    filename: 'types/nuxt-mdream.d.ts',
    getContents: () => `// Generated by nuxt-mdream

declare module '@nuxt/schema' {
  interface RuntimeConfig {
    mdream: {
      enabled: boolean
      mdreamOptions: Record<string, any>
      cache: {
        maxAge: number
        swr: boolean
      }
    }
  }

  interface NuxtHooks {
    'mdream:llms-txt': (payload: import('${typesPath}').MdreamLlmsTxtGeneratePayload) => void | Promise<void>
  }
}

export {}
`,
  }, { nuxt: true, node: true })

  addTypeTemplate({
    filename: 'types/nuxt-mdream-nitro.d.ts',
    getContents: () => `// Generated by nuxt-mdream

declare module 'nitropack/types' {
  interface NitroRuntimeHooks {
    'mdream:negotiate': (context: import('${typesPath}').MdreamNegotiateContext) => void | Promise<void>
    'mdream:markdown': (context: import('${typesPath}').MdreamMarkdownContext) => void | Promise<void>
    'mdream:config': (config: import('mdream').HTMLToMarkdownOptions) => void | Promise<void>
  }
}

declare module 'nitropack' {
  interface NitroRuntimeHooks {
    'mdream:negotiate': (context: import('${typesPath}').MdreamNegotiateContext) => void | Promise<void>
    'mdream:markdown': (context: import('${typesPath}').MdreamMarkdownContext) => void | Promise<void>
    'mdream:config': (config: import('mdream').HTMLToMarkdownOptions) => void | Promise<void>
  }
}

export {}
`,
  }, { nitro: true, node: true })
}
