import type { TagHandler } from './types'
import {
  TAG_A,
  TAG_ABBR,
  TAG_AREA,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BR,
  TAG_BUTTON,
  TAG_CITE,
  TAG_CODE,
  TAG_DEL,
  TAG_DFN,
  TAG_EM,
  TAG_FIGCAPTION,
  TAG_I,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LINK,
  TAG_MARK,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SMALL,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_SUB,
  TAG_SUP,
  TAG_TIME,
  TAG_U,
  TAG_VAR,
  TAG_WBR,
} from './const'
import { parserTagHandlers } from './parser-tags'

/**
 * Inline HTML elements. Whitespace around them belongs to the surrounding
 * text, so output formats that keep source spacing need this metadata.
 */
export const INLINE_TAG_IDS: number[] = [
  TAG_A,
  TAG_ABBR,
  TAG_AREA,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BR,
  TAG_BUTTON,
  TAG_CITE,
  TAG_CODE,
  TAG_DEL,
  TAG_DFN,
  TAG_EM,
  TAG_FIGCAPTION,
  TAG_I,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LINK,
  TAG_MARK,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SMALL,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_SUB,
  TAG_SUP,
  TAG_TIME,
  TAG_U,
  TAG_VAR,
  TAG_WBR,
]

/** `parserTagHandlers` plus inline metadata, for HTML-shaped output. */
export const htmlTagHandlers: Record<number, TagHandler> = { ...parserTagHandlers }
for (const tagId of INLINE_TAG_IDS)
  htmlTagHandlers[tagId] = { ...htmlTagHandlers[tagId], isInline: true }
