import type { TagHandler } from './types'
import {
  TAG_AREA,
  TAG_BASE,
  TAG_BR,
  TAG_COL,
  TAG_DATALIST,
  TAG_EMBED,
  TAG_HR,
  TAG_IFRAME,
  TAG_IMG,
  TAG_INPUT,
  TAG_KEYGEN,
  TAG_LINK,
  TAG_META,
  TAG_NOEMBED,
  TAG_NOFRAMES,
  TAG_NOSCRIPT,
  TAG_PARAM,
  TAG_PLAINTEXT,
  TAG_SCRIPT,
  TAG_SOURCE,
  TAG_STYLE,
  TAG_TBODY,
  TAG_TEMPLATE,
  TAG_TEXTAREA,
  TAG_TFOOT,
  TAG_THEAD,
  TAG_TITLE,
  TAG_TR,
  TAG_TRACK,
  TAG_WBR,
  TAG_XMP,
} from './const'

const selfClosing = { isSelfClosing: true }
const rawText = { isNonNesting: true }
const inertRawText = { isNonNesting: true, excludesTextNodes: true }

/** HTML parsing metadata with no output-format behavior. */
export const parserTagHandlers: Record<number, TagHandler> = {
  [TAG_TITLE]: rawText,
  [TAG_SCRIPT]: inertRawText,
  [TAG_STYLE]: inertRawText,
  [TAG_META]: selfClosing,
  [TAG_BR]: selfClosing,
  [TAG_HR]: selfClosing,
  [TAG_IMG]: selfClosing,
  [TAG_THEAD]: { excludesTextNodes: true },
  [TAG_TR]: { excludesTextNodes: true },
  [TAG_TBODY]: { excludesTextNodes: true },
  [TAG_TFOOT]: { excludesTextNodes: true },
  [TAG_LINK]: selfClosing,
  [TAG_AREA]: selfClosing,
  [TAG_BASE]: selfClosing,
  [TAG_COL]: selfClosing,
  [TAG_EMBED]: selfClosing,
  [TAG_INPUT]: selfClosing,
  [TAG_KEYGEN]: selfClosing,
  [TAG_PARAM]: selfClosing,
  [TAG_SOURCE]: selfClosing,
  [TAG_TRACK]: selfClosing,
  [TAG_WBR]: selfClosing,
  [TAG_TEXTAREA]: rawText,
  [TAG_IFRAME]: inertRawText,
  [TAG_TEMPLATE]: { excludesTextNodes: true },
  [TAG_NOSCRIPT]: inertRawText,
  [TAG_NOEMBED]: inertRawText,
  [TAG_DATALIST]: inertRawText,
  [TAG_NOFRAMES]: inertRawText,
  [TAG_XMP]: rawText,
  [TAG_PLAINTEXT]: rawText,
}
