import type { TagHandler } from './types'
import {
  TAG_A,
  TAG_ABBR,
  TAG_AREA,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BR,
  TAG_BUTTON,
  TAG_CITE,
  TAG_CODE,
  TAG_COL,
  TAG_DATALIST,
  TAG_DEL,
  TAG_DFN,
  TAG_EM,
  TAG_EMBED,
  TAG_FIGCAPTION,
  TAG_HR,
  TAG_I,
  TAG_IFRAME,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LINK,
  TAG_MARK,
  TAG_META,
  TAG_NOEMBED,
  TAG_NOFRAMES,
  TAG_NOSCRIPT,
  TAG_PARAM,
  TAG_PLAINTEXT,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SCRIPT,
  TAG_SMALL,
  TAG_SOURCE,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_STYLE,
  TAG_SUB,
  TAG_SUP,
  TAG_TBODY,
  TAG_TEMPLATE,
  TAG_TEXTAREA,
  TAG_TFOOT,
  TAG_THEAD,
  TAG_TIME,
  TAG_TITLE,
  TAG_TR,
  TAG_TRACK,
  TAG_U,
  TAG_VAR,
  TAG_WBR,
  TAG_XMP,
} from './const'

const selfClosing = { isSelfClosing: true }
const rawText = { isNonNesting: true }
const inertRawText = { isNonNesting: true, excludesTextNodes: true }

/** HTML parsing metadata with no output-format behavior. */
export const parserTagHandlers: Record<number, TagHandler> = {
  [TAG_TITLE]: rawText,
  [TAG_SCRIPT]: inertRawText,
  [TAG_STYLE]: inertRawText,
  [TAG_META]: selfClosing,
  [TAG_BR]: selfClosing,
  [TAG_HR]: selfClosing,
  [TAG_IMG]: selfClosing,
  [TAG_THEAD]: { excludesTextNodes: true },
  [TAG_TR]: { excludesTextNodes: true },
  [TAG_TBODY]: { excludesTextNodes: true },
  [TAG_TFOOT]: { excludesTextNodes: true },
  [TAG_LINK]: selfClosing,
  [TAG_AREA]: selfClosing,
  [TAG_BASE]: selfClosing,
  [TAG_COL]: selfClosing,
  [TAG_EMBED]: selfClosing,
  [TAG_INPUT]: selfClosing,
  [TAG_KEYGEN]: selfClosing,
  [TAG_PARAM]: selfClosing,
  [TAG_SOURCE]: selfClosing,
  [TAG_TRACK]: selfClosing,
  [TAG_WBR]: selfClosing,
  [TAG_TEXTAREA]: rawText,
  [TAG_IFRAME]: inertRawText,
  [TAG_TEMPLATE]: { excludesTextNodes: true },
  [TAG_NOSCRIPT]: inertRawText,
  [TAG_NOEMBED]: inertRawText,
  [TAG_DATALIST]: inertRawText,
  [TAG_NOFRAMES]: inertRawText,
  [TAG_XMP]: rawText,
  [TAG_PLAINTEXT]: rawText,
}

/**
 * Inline HTML elements. Whitespace around them belongs to the surrounding
 * text, so output formats that keep source spacing need this metadata.
 */
export const INLINE_TAG_IDS: number[] = [
  TAG_A,
  TAG_ABBR,
  TAG_AREA,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BR,
  TAG_BUTTON,
  TAG_CITE,
  TAG_CODE,
  TAG_DEL,
  TAG_DFN,
  TAG_EM,
  TAG_FIGCAPTION,
  TAG_I,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LINK,
  TAG_MARK,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SMALL,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_SUB,
  TAG_SUP,
  TAG_TIME,
  TAG_U,
  TAG_VAR,
  TAG_WBR,
]

/** `parserTagHandlers` plus inline metadata, for HTML-shaped output. */
export const htmlTagHandlers: Record<number, TagHandler> = { ...parserTagHandlers }
for (const tagId of INLINE_TAG_IDS)
  htmlTagHandlers[tagId] = { ...htmlTagHandlers[tagId], isInline: true }
