import type { TagHandler } from './types'
import {
  DEFAULT_BLOCK_SPACING,
  LIST_ITEM_SPACING,
  NO_SPACING,
  TABLE_ROW_SPACING,
  TAG_A,
  TAG_ABBR,
  TAG_ADDRESS,
  TAG_AREA,
  TAG_ASIDE,
  TAG_AUDIO,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BLOCKQUOTE,
  TAG_BODY,
  TAG_BR,
  TAG_BUTTON,
  TAG_CANVAS,
  TAG_CENTER,
  TAG_CITE,
  TAG_CODE,
  TAG_COL,
  TAG_DATALIST,
  TAG_DD,
  TAG_DEL,
  TAG_DFN,
  TAG_DIALOG,
  TAG_DL,
  TAG_DT,
  TAG_EM,
  TAG_EMBED,
  TAG_FIELDSET,
  TAG_FIGCAPTION,
  TAG_FOOTER,
  TAG_FORM,
  TAG_H1,
  TAG_H2,
  TAG_H3,
  TAG_H4,
  TAG_H5,
  TAG_H6,
  TAG_HEAD,
  TAG_I,
  TAG_IFRAME,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LEGEND,
  TAG_LI,
  TAG_LINK,
  TAG_MAP,
  TAG_MARK,
  TAG_META,
  TAG_METER,
  TAG_NOEMBED,
  TAG_NOFRAMES,
  TAG_NOSCRIPT,
  TAG_OPTGROUP,
  TAG_OPTION,
  TAG_PARAM,
  TAG_PLAINTEXT,
  TAG_PROGRESS,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SELECT,
  TAG_SMALL,
  TAG_SOURCE,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_SUB,
  TAG_SUP,
  TAG_SVG,
  TAG_TBODY,
  TAG_TD,
  TAG_TEMPLATE,
  TAG_TEXTAREA,
  TAG_TFOOT,
  TAG_TH,
  TAG_THEAD,
  TAG_TIME,
  TAG_TITLE,
  TAG_TR,
  TAG_TRACK,
  TAG_U,
  TAG_VAR,
  TAG_VIDEO,
  TAG_WBR,
  TAG_XMP,
} from './const'
import { parserTagHandlers } from './parser-tags'

export const textTagHandlers: Record<number, TagHandler> = { ...parserTagHandlers }

function assign(tagIds: number[], metadata: TagHandler): void {
  for (const tagId of tagIds)
    textTagHandlers[tagId] = { ...textTagHandlers[tagId], ...metadata }
}

const inline = { collapsesInnerWhiteSpace: true, isInline: true, spacing: NO_SPACING }
assign([
  TAG_STRONG,
  TAG_B,
  TAG_EM,
  TAG_I,
  TAG_DEL,
  TAG_S,
  TAG_STRIKE,
  TAG_SUB,
  TAG_SUP,
  TAG_INS,
  TAG_CODE,
  TAG_A,
  TAG_IMG,
  TAG_SPAN,
  TAG_LABEL,
  TAG_BUTTON,
  TAG_KBD,
  TAG_AREA,
  TAG_BASE,
  TAG_INPUT,
  TAG_KEYGEN,
  TAG_WBR,
  TAG_ABBR,
  TAG_MARK,
  TAG_Q,
  TAG_SAMP,
  TAG_SMALL,
  TAG_U,
  TAG_CITE,
  TAG_DFN,
  TAG_VAR,
  TAG_TIME,
  TAG_BDO,
  TAG_RUBY,
  TAG_RT,
  TAG_RP,
], inline)

// A caption owns its own block boundary, so it carries no fixed spacing.
assign([TAG_FIGCAPTION], { collapsesInnerWhiteSpace: true, isInline: true })

assign([
  TAG_HEAD,
  TAG_META,
  TAG_BR,
  TAG_TH,
  TAG_TD,
  TAG_TBODY,
  TAG_BODY,
  TAG_CENTER,
  TAG_FOOTER,
  TAG_FORM,
  TAG_LINK,
  TAG_COL,
  TAG_EMBED,
  TAG_PARAM,
  TAG_SOURCE,
  TAG_TRACK,
  TAG_SELECT,
  TAG_TITLE,
  TAG_OPTION,
  TAG_OPTGROUP,
  TAG_FIELDSET,
  TAG_LEGEND,
  TAG_SVG,
  TAG_NOSCRIPT,
  TAG_NOEMBED,
  TAG_DATALIST,
  TAG_NOFRAMES,
], { spacing: NO_SPACING })

assign([TAG_THEAD, TAG_TR, TAG_TFOOT], { spacing: TABLE_ROW_SPACING })
assign([TAG_LI], { spacing: LIST_ITEM_SPACING })
assign([TAG_DD], { spacing: [0, 1] })

// Whitespace and spacing metadata the markdown table already carried. Plain
// text reads the same fields, so both formats break a document the same way.
assign([TAG_BR, TAG_LINK], { collapsesInnerWhiteSpace: true, isInline: true })
assign([
  TAG_ASIDE,
  TAG_AUDIO,
  TAG_CANVAS,
  TAG_DIALOG,
  TAG_DL,
  TAG_IFRAME,
  TAG_MAP,
  TAG_METER,
  TAG_PLAINTEXT,
  TAG_PROGRESS,
  TAG_TEMPLATE,
  TAG_TEXTAREA,
  TAG_VIDEO,
  TAG_XMP,
], { spacing: NO_SPACING })
assign([TAG_ADDRESS], { collapsesInnerWhiteSpace: true, spacing: NO_SPACING })
assign([
  TAG_H1,
  TAG_H2,
  TAG_H3,
  TAG_H4,
  TAG_H5,
  TAG_H6,
  TAG_HEAD,
  TAG_META,
  TAG_TD,
  TAG_TH,
  TAG_TITLE,
], { collapsesInnerWhiteSpace: true })
assign([TAG_BLOCKQUOTE], { spacing: DEFAULT_BLOCK_SPACING })
assign([TAG_DT], { collapsesInnerWhiteSpace: true, spacing: [0, 1] })
