import type { TagHandler } from './types'
import {
  LIST_ITEM_SPACING,
  NO_SPACING,
  TABLE_ROW_SPACING,
  TAG_A,
  TAG_ABBR,
  TAG_AREA,
  TAG_B,
  TAG_BASE,
  TAG_BDO,
  TAG_BODY,
  TAG_BR,
  TAG_BUTTON,
  TAG_CENTER,
  TAG_CITE,
  TAG_CODE,
  TAG_COL,
  TAG_DATALIST,
  TAG_DD,
  TAG_DEL,
  TAG_DFN,
  TAG_EM,
  TAG_EMBED,
  TAG_FIELDSET,
  TAG_FIGCAPTION,
  TAG_FOOTER,
  TAG_FORM,
  TAG_HEAD,
  TAG_I,
  TAG_IMG,
  TAG_INPUT,
  TAG_INS,
  TAG_KBD,
  TAG_KEYGEN,
  TAG_LABEL,
  TAG_LEGEND,
  TAG_LI,
  TAG_LINK,
  TAG_MARK,
  TAG_META,
  TAG_NOEMBED,
  TAG_NOFRAMES,
  TAG_NOSCRIPT,
  TAG_OPTGROUP,
  TAG_OPTION,
  TAG_PARAM,
  TAG_Q,
  TAG_RP,
  TAG_RT,
  TAG_RUBY,
  TAG_S,
  TAG_SAMP,
  TAG_SELECT,
  TAG_SMALL,
  TAG_SOURCE,
  TAG_SPAN,
  TAG_STRIKE,
  TAG_STRONG,
  TAG_SUB,
  TAG_SUP,
  TAG_SVG,
  TAG_TBODY,
  TAG_TD,
  TAG_TFOOT,
  TAG_TH,
  TAG_THEAD,
  TAG_TIME,
  TAG_TITLE,
  TAG_TR,
  TAG_TRACK,
  TAG_U,
  TAG_VAR,
  TAG_WBR,
} from './const'
import { parserTagHandlers } from './parser-tags'

export const textTagHandlers: Record<number, TagHandler> = { ...parserTagHandlers }

function assign(tagIds: number[], metadata: TagHandler): void {
  for (const tagId of tagIds)
    textTagHandlers[tagId] = { ...textTagHandlers[tagId], ...metadata }
}

const inline = { collapsesInnerWhiteSpace: true, isInline: true, spacing: NO_SPACING }
assign([
  TAG_STRONG,
  TAG_B,
  TAG_EM,
  TAG_I,
  TAG_DEL,
  TAG_S,
  TAG_STRIKE,
  TAG_SUB,
  TAG_SUP,
  TAG_INS,
  TAG_CODE,
  TAG_A,
  TAG_IMG,
  TAG_SPAN,
  TAG_LABEL,
  TAG_BUTTON,
  TAG_KBD,
  TAG_AREA,
  TAG_BASE,
  TAG_INPUT,
  TAG_KEYGEN,
  TAG_WBR,
  TAG_ABBR,
  TAG_MARK,
  TAG_Q,
  TAG_SAMP,
  TAG_SMALL,
  TAG_U,
  TAG_CITE,
  TAG_DFN,
  TAG_VAR,
  TAG_TIME,
  TAG_BDO,
  TAG_RUBY,
  TAG_RT,
  TAG_RP,
  TAG_FIGCAPTION,
], inline)

assign([
  TAG_HEAD,
  TAG_META,
  TAG_BR,
  TAG_TH,
  TAG_TD,
  TAG_TBODY,
  TAG_BODY,
  TAG_CENTER,
  TAG_FOOTER,
  TAG_FORM,
  TAG_LINK,
  TAG_COL,
  TAG_EMBED,
  TAG_PARAM,
  TAG_SOURCE,
  TAG_TRACK,
  TAG_SELECT,
  TAG_TITLE,
  TAG_OPTION,
  TAG_OPTGROUP,
  TAG_FIELDSET,
  TAG_LEGEND,
  TAG_SVG,
  TAG_NOSCRIPT,
  TAG_NOEMBED,
  TAG_DATALIST,
  TAG_NOFRAMES,
], { spacing: NO_SPACING })

assign([TAG_THEAD, TAG_TR, TAG_TFOOT], { spacing: TABLE_ROW_SPACING })
assign([TAG_LI], { spacing: LIST_ITEM_SPACING })
assign([TAG_DD], { spacing: [0, 1] })
