packages:
  - playground
  - packages/*
  - examples/*
onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
  - workerd
  - maplibre-gl
catalog:
  '@actions/core': ^1.11.1
  '@actions/exec': ^1.1.1
  '@antfu/eslint-config': ^6.4.2
  '@arethetypeswrong/cli': ^0.18.2
  '@aws-sdk/client-s3': ^3.946.0
  '@built-in-ai/transformers-js': ^0.3.3
  '@clack/prompts': ^0.11.0
  '@iconify-json/carbon': ^1.2.15
  '@iconify-json/heroicons': ^1.2.3
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/material-symbols': ^1.2.49
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/radix-icons': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.61
  '@iconify-json/uil': ^1.2.3
  '@iconify-json/unjs': ^1.2.3
  '@iconify-json/vscode-icons': ^1.2.37
  '@inspira-ui/plugins': ^0.0.1
  '@libsql/client': ^0.15.15
  '@nuxt/content': 3.5.1
  '@nuxt/devtools': 2.4.0
  '@nuxt/fonts': ^0.12.1
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': ^4.2.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.2.1
  '@nuxt/scripts': ^0.13.0
  '@nuxt/test-utils': ^3.21.0
  '@nuxt/ui-pro': ^3.3.7
  '@nuxthub/core': 0.8.27
  '@nuxtjs/mdc': 0.17.0
  '@nuxtjs/seo': ^3.2.2
  '@types/better-sqlite3': ^7.6.13
  '@types/express': ^5.0.6
  '@types/node': ^24.10.1
  '@types/picomatch': ^4.0.2
  '@unovis/vue': 1.5.1
  '@vercel/ncc': ^0.38.4
  '@vitejs/plugin-vue': ^6.0.2
  '@vitest/browser': ^3.2.4
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  ai: ^5.0.108
  better-sqlite3: ^12.5.0
  bumpp: ^10.3.2
  cac: ^6.7.14
  case-police: ^2.1.1
  changelogen: ^0.6.2
  clsx: ^2.1.1
  compression: ^1.8.1
  consola: ^3.4.2
  crawlee: ^3.15.3
  cross-env: ^10.1.0
  defu: ^6.1.4
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.0
  eslint: ^9.39.1
  express: ^5.2.1
  jsdom: ^27.2.0
  llm-cost: ^1.0.5
  markdownlint-cli: ^0.46.0
  motion-v: 1.1.0-alpha.0
  nuxt: ^4.2.1
  nuxt-build-cache: ^0.1.1
  nuxt-content-twoslash: ^0.1.2
  nuxt-llms: ^0.1.3
  nuxt-lodash: ^2.5.3
  nuxt-rebundle: ^0.0.2
  nuxt-site-config: ^3.2.11
  nypm: ^0.6.2
  obuild: ^0.4.7
  octokit: ^5.0.5
  ofetch: ^1.5.1
  pathe: ^2.0.3
  picomatch: ^4.0.3
  playwright: ^1.57.0
  radix-vue: ^1.9.17
  shiki: 3.4.0
  shiki-magic-move: ^1.2.1
  shiki-transformer-color-highlight: ^1.0.0
  sirv: ^3.0.2
  sponsorkit: ^17.0.0
  tailwind-merge: ^3.4.0
  tailwindcss-animate: ^1.0.7
  tinyglobby: ^0.2.15
  typescript: ^5.9.3
  ufo: ^1.6.1
  unstorage: ^1.17.3
  vite: ^7.2.7
  vitest: ^3.2.4
  vue: ^3.5.25
  vue-router: ^4.6.3
  wrangler: ^4.53.0
overrides:
  vite: npm:rolldown-vite@latest
catalogs:
  conflicts_@nuxt/devtools_latest:
    '@nuxt/devtools': latest
  conflicts_@types/node_latest:
    '@types/node': latest
