import type { ProcessedFile } from '../../src/llms-txt'
import { describe, expect, it } from 'vitest'
import { generateLlmsTxtArtifacts } from '../../src/llms-txt'

function makeFile(overrides: Partial<ProcessedFile> = {}): ProcessedFile {
  return {
    title: 'Test Page',
    content: '# Test Page\n\nSome content here.',
    url: '/test',
    ...overrides,
  }
}

describe('generateLlmsTxtArtifacts', () => {
  describe('llms.txt generation', () => {
    it('generates basic llms.txt with site name header', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile()],
        siteName: 'My Site',
      })
      expect(result.llmsTxt).toContain('# My Site')
      expect(result.llmsTxt).toContain('## Pages')
      expect(result.llmsTxt).toContain('- [Test Page](/test)')
    })

    it('defaults siteName to "Site"', async () => {
      const result = await generateLlmsTxtArtifacts({ files: [] })
      expect(result.llmsTxt).toContain('# Site')
    })

    it('includes description as blockquote', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [],
        siteName: 'Test',
        description: 'A test site',
      })
      expect(result.llmsTxt).toContain('> A test site')
    })

    it('includes canonical origin', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile()],
        origin: 'https://example.com',
      })
      expect(result.llmsTxt).toContain('Canonical Origin: https://example.com')
      expect(result.llmsTxt).toContain('- [Test Page](https://example.com/test)')
    })

    it('uses full URL directly when file.url starts with http', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({ url: 'https://cdn.example.com/page' })],
        origin: 'https://example.com',
      })
      expect(result.llmsTxt).toContain('- [Test Page](https://cdn.example.com/page)')
    })

    it('truncates description at 100 chars in llms.txt links', async () => {
      const longDesc = 'A'.repeat(120)
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({ metadata: { description: longDesc } })],
      })
      expect(result.llmsTxt).toContain(`${'A'.repeat(100)}...`)
    })

    it('handles empty files array', async () => {
      const result = await generateLlmsTxtArtifacts({ files: [] })
      expect(result.llmsTxt).toContain('# Site')
      expect(result.llmsTxt).not.toContain('## Pages')
    })

    it('renders custom sections before pages', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile()],
        sections: [{
          title: 'API Reference',
          description: 'REST API docs',
          links: [
            { title: 'Auth', href: '/api/auth', description: 'Authentication endpoints' },
          ],
        }],
      })
      expect(result.llmsTxt).toContain('## API Reference')
      expect(result.llmsTxt).toContain('REST API docs')
      expect(result.llmsTxt).toContain('- [Auth](/api/auth): Authentication endpoints')
    })

    it('renders section with array description', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [],
        sections: [{
          title: 'About',
          description: ['First paragraph.', 'Second paragraph.'],
        }],
      })
      expect(result.llmsTxt).toContain('First paragraph.\n\nSecond paragraph.')
    })

    it('renders notes at the end', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [],
        notes: 'Generated by mdream',
      })
      expect(result.llmsTxt).toContain('Generated by mdream')
    })

    it('renders array notes', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [],
        notes: ['Note 1', 'Note 2'],
      })
      expect(result.llmsTxt).toContain('Note 1')
      expect(result.llmsTxt).toContain('Note 2')
    })
  })

  describe('llms-full.txt generation', () => {
    it('does not generate llms-full.txt by default', async () => {
      const result = await generateLlmsTxtArtifacts({ files: [makeFile()] })
      expect(result.llmsFullTxt).toBeUndefined()
    })

    it('generates llms-full.txt with generateFull: true', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile()],
        siteName: 'Test',
        generateFull: true,
      })
      expect(result.llmsFullTxt).toBeDefined()
      expect(result.llmsFullTxt).toContain('# Test')
      expect(result.llmsFullTxt).toContain('## Table of Contents')
      expect(result.llmsFullTxt).toContain('Some content here.')
    })

    it('includes frontmatter in llms-full.txt entries', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({
          metadata: { description: 'A test page', author: 'Jane' },
        })],
        generateFull: true,
        origin: 'https://example.com',
      })
      expect(result.llmsFullTxt).toContain('title: Test Page')
      expect(result.llmsFullTxt).toContain('url: https://example.com/test')
      expect(result.llmsFullTxt).toContain('description: A test page')
      expect(result.llmsFullTxt).toContain('author: Jane')
    })

    it('generates table of contents with anchor links', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [
          makeFile({ title: 'Getting Started', url: '/getting-started' }),
          makeFile({ title: 'API Docs', url: '/api' }),
        ],
        generateFull: true,
      })
      expect(result.llmsFullTxt).toContain('- [Getting Started](#getting-started)')
      expect(result.llmsFullTxt).toContain('- [API Docs](#api-docs)')
    })

    it('removes duplicate title from content body', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({
          title: 'Test Page',
          content: '# Test Page\n\nBody text.',
        })],
        generateFull: true,
      })
      // Title appears in frontmatter but not duplicated as heading in body
      const bodyAfterFrontmatter = result.llmsFullTxt!.split('---').slice(3).join('---')
      expect(bodyAfterFrontmatter).not.toContain('# Test Page')
      expect(bodyAfterFrontmatter).toContain('Body text.')
    })

    it('merges existing frontmatter in content', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({
          content: '---\ncustom: value\n---\n\nBody text.',
        })],
        generateFull: true,
      })
      expect(result.llmsFullTxt).toContain('custom: value')
      expect(result.llmsFullTxt).toContain('title: Test Page')
    })
  })

  describe('markdown files generation', () => {
    it('does not generate markdown files by default', async () => {
      const result = await generateLlmsTxtArtifacts({ files: [makeFile()] })
      expect(result.markdownFiles).toBeUndefined()
    })

    it('generates markdown files with generateMarkdown: true', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [
          makeFile({ url: '/about', content: '# About\n\nAbout us.' }),
          makeFile({ url: '/blog/post1', content: '# Post 1\n\nContent.' }),
        ],
        generateMarkdown: true,
      })
      expect(result.markdownFiles).toHaveLength(2)
      expect(result.markdownFiles![0]!.path).toBe('md/about.md')
      expect(result.markdownFiles![0]!.content).toBe('# About\n\nAbout us.')
      expect(result.markdownFiles![1]!.path).toBe('md/blog/post1.md')
    })

    it('maps root URL to md/index.md', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({ url: '/' })],
        generateMarkdown: true,
      })
      expect(result.markdownFiles![0]!.path).toBe('md/index.md')
    })

    it('strips leading and trailing slashes from URL path', async () => {
      const result = await generateLlmsTxtArtifacts({
        files: [makeFile({ url: '/docs/guide/' })],
        generateMarkdown: true,
      })
      expect(result.markdownFiles![0]!.path).toBe('md/docs/guide.md')
    })
  })

  describe('processedFiles passthrough', () => {
    it('returns input files as processedFiles', async () => {
      const files = [makeFile(), makeFile({ url: '/other', title: 'Other' })]
      const result = await generateLlmsTxtArtifacts({ files })
      expect(result.processedFiles).toBe(files)
    })
  })
})
