/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MarkdownStream {
  constructor(options?: HtmlToMarkdownOptions | undefined | null)
  processChunk(chunk: string): string
  finish(): string
}

export interface FilterOptions {
  include?: Array<string>
  exclude?: Array<string>
  processChildren?: boolean
}

export interface FrontmatterOptions {
  additionalFields?: Record<string, string>
  metaFields?: Array<string>
}

export declare function htmlToMarkdown(html: string, options?: HtmlToMarkdownOptions | undefined | null): string

export interface HtmlToMarkdownOptions {
  origin?: string
  plugins?: PluginOptions
}

export interface PluginOptions {
  filter?: FilterOptions
  isolateMain?: boolean
  frontmatter?: FrontmatterOptions
  tailwind?: boolean
}
