/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class MarkdownStream {
  constructor(options?: HtmlToMarkdownOptions | undefined | null)
  processChunk(chunk: string): string
  processChunkBytes(chunk: Uint8Array): string
  finish(): string
  /**
   * Frontmatter and extracted elements collected so far. Call after
   * `finish()` for the complete data. Extracted elements drain on each call.
   */
  takeData(): MdreamStreamData
}

export interface CleanOptionsNapi {
  urls?: boolean
  fragments?: boolean
  emptyLinks?: boolean
  redundantLinks?: boolean
  selfLinkHeadings?: boolean
  emptyImages?: boolean
  emptyLinkText?: boolean
}

export interface ExtractedElementNapi {
  selector: string
  tagName: string
  textContent: string
  attributes: Record<string, string>
}

export interface ExtractionOptions {
  selectors: Array<string>
}

export interface FilterOptions {
  include?: Array<string>
  exclude?: Array<string>
  processChildren?: boolean
}

export interface FrontmatterOptions {
  additionalFields?: Record<string, string>
  metaFields?: Array<string>
}

export declare function htmlToMarkdown(html: string, options?: HtmlToMarkdownOptions | undefined | null): MdreamNapiResult

export declare function htmlToMarkdownBytes(html: Uint8Array, options?: HtmlToMarkdownOptions | undefined | null): MdreamNapiResult

export interface HtmlToMarkdownOptions {
  origin?: string
  clean?: CleanOptionsNapi
  plugins?: PluginOptions
  wrapWidth?: number
  format?: "markdown" | "text" | "html"
}

export interface MdreamNapiResult {
  markdown: string
  extracted?: Array<ExtractedElementNapi>
  frontmatter?: Record<string, string>
}

/** Plugin data a stream collected: frontmatter and extracted elements. */
export interface MdreamStreamData {
  extracted?: Array<ExtractedElementNapi>
  frontmatter?: Record<string, string>
}

export interface PluginOptions {
  filter?: FilterOptions
  isolateMain?: boolean
  frontmatter?: FrontmatterOptions
  tailwind?: boolean
  extraction?: ExtractionOptions
  tagOverrides?: Record<string, TagOverrideNapi>
}

export interface TagOverrideNapi {
  enter?: string
  exit?: string
  spacing?: Array<number>
  isInline?: boolean
  isSelfClosing?: boolean
  collapsesInnerWhiteSpace?: boolean
  alias?: string
}
