/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MarkdownStream {
  constructor(options?: HtmlToMarkdownOptions | undefined | null)
  processChunk(chunk: string): string
  processChunkBytes(chunk: Uint8Array): string
  finish(): string
}

export interface ChunkLocNapi {
  from: number
  to: number
}

export interface ChunkMetadataNapi {
  headers?: Record<string, string>
  code?: string
  loc?: ChunkLocNapi
}

export interface CleanOptionsNapi {
  urls?: boolean
  fragments?: boolean
  emptyLinks?: boolean
  blankLines?: boolean
  redundantLinks?: boolean
  selfLinkHeadings?: boolean
  emptyImages?: boolean
  emptyLinkText?: boolean
}

export interface ExtractedElementNapi {
  selector: string
  tagName: string
  textContent: string
  attributes: Record<string, string>
}

export interface ExtractionOptions {
  selectors: Array<string>
}

export interface FilterOptions {
  include?: Array<string>
  exclude?: Array<string>
  processChildren?: boolean
}

export interface FrontmatterOptions {
  additionalFields?: Record<string, string>
  metaFields?: Array<string>
}

export declare function htmlToMarkdown(html: string, options?: HtmlToMarkdownOptions | undefined | null): MdreamNapiResult

export declare function htmlToMarkdownBytes(html: Uint8Array, options?: HtmlToMarkdownOptions | undefined | null): MdreamNapiResult

export declare function htmlToMarkdownChunks(html: string, options?: HtmlToMarkdownOptions | undefined | null, splitterOptions?: SplitterOptionsNapi | undefined | null): Array<MarkdownChunkNapi>

export interface HtmlToMarkdownOptions {
  origin?: string
  cleanUrls?: boolean
  clean?: CleanOptionsNapi
  plugins?: PluginOptions
}

export interface MarkdownChunkNapi {
  content: string
  metadata: ChunkMetadataNapi
}

export interface MdreamNapiResult {
  markdown: string
  extracted?: Array<ExtractedElementNapi>
  frontmatter?: Record<string, string>
}

export interface PluginOptions {
  filter?: FilterOptions
  isolateMain?: boolean
  frontmatter?: FrontmatterOptions
  tailwind?: boolean
  extraction?: ExtractionOptions
  tagOverrides?: Record<string, TagOverrideNapi>
}

export declare function splitMarkdown(markdown: string, options?: SplitterOptionsNapi | undefined | null): Array<MarkdownChunkNapi>

export interface SplitterOptionsNapi {
  headersToSplitOn?: Array<number>
  returnEachLine?: boolean
  stripHeaders?: boolean
  chunkSize?: number
  chunkOverlap?: number
}

export interface TagOverrideNapi {
  enter?: string
  exit?: string
  spacing?: Array<number>
  isInline?: boolean
  isSelfClosing?: boolean
  collapsesInnerWhiteSpace?: boolean
  alias?: string
}
