packages: []
minimumReleaseAgeExclude:
  - '@types/node@26.6.4'
  - '@mdream/rust-android-arm-eabi@2.0.0-beta.1'
  - '@mdream/rust-android-arm64@2.0.0-beta.1'
  - '@mdream/rust-darwin-arm64@2.0.0-beta.1'
  - '@mdream/rust-darwin-x64@2.0.0-beta.1'
  - '@mdream/rust-freebsd-x64@2.0.0-beta.1'
  - '@mdream/rust-linux-arm-gnueabihf@2.0.0-beta.1'
  - '@mdream/rust-linux-arm64-gnu@2.0.0-beta.1'
  - '@mdream/rust-linux-arm64-musl@2.0.0-beta.1'
  - '@mdream/rust-linux-x64-gnu@2.0.0-beta.1'
  - '@mdream/rust-linux-x64-musl@2.0.0-beta.1'
  - '@mdream/rust-wasm32-wasi@2.0.0-beta.1'
  - '@mdream/rust-win32-arm64-msvc@2.0.0-beta.1'
  - '@mdream/rust-win32-x64-msvc@2.0.0-beta.1'
  - mdream@2.0.0-beta.1
