// Generated by scripts/generate-html-entities.mjs from the WHATWG table.
// Keep this file in parity with packages/js/src/entities.ts.

pub(super) const MAX_ENTITY_NAME_LENGTH: usize = 31;
pub(super) const MAX_LEGACY_ENTITY_NAME_LENGTH: usize = 6;

#[inline]
pub(super) fn lookup_named_entity(name: &[u8]) -> Option<&'static str> {
  match name {
    b"AElig" => Some("\u{C6}"),
    b"AMP" => Some("&"),
    b"Aacute" => Some("\u{C1}"),
    b"Acirc" => Some("\u{C2}"),
    b"Agrave" => Some("\u{C0}"),
    b"Alpha" => Some("\u{391}"),
    b"Aring" => Some("\u{C5}"),
    b"Atilde" => Some("\u{C3}"),
    b"Auml" => Some("\u{C4}"),
    b"Beta" => Some("\u{392}"),
    b"COPY" => Some("\u{A9}"),
    b"Ccedil" => Some("\u{C7}"),
    b"Cedilla" => Some("\u{B8}"),
    b"CenterDot" => Some("\u{B7}"),
    b"Chi" => Some("\u{3A7}"),
    b"CirclePlus" => Some("\u{2295}"),
    b"CircleTimes" => Some("\u{2297}"),
    b"CloseCurlyDoubleQuote" => Some("\u{201D}"),
    b"CloseCurlyQuote" => Some("\u{2019}"),
    b"Congruent" => Some("\u{2261}"),
    b"CounterClockwiseContourIntegral" => Some("\u{2233}"),
    b"Dagger" => Some("\u{2021}"),
    b"Del" => Some("\u{2207}"),
    b"Delta" => Some("\u{394}"),
    b"DiacriticalAcute" => Some("\u{B4}"),
    b"DiacriticalGrave" => Some("`"),
    b"DiacriticalTilde" => Some("\u{2DC}"),
    b"Dot" => Some("\u{A8}"),
    b"DoubleDot" => Some("\u{A8}"),
    b"DoubleDownArrow" => Some("\u{21D3}"),
    b"DoubleLeftArrow" => Some("\u{21D0}"),
    b"DoubleLeftRightArrow" => Some("\u{21D4}"),
    b"DoubleRightArrow" => Some("\u{21D2}"),
    b"DoubleUpArrow" => Some("\u{21D1}"),
    b"DownArrow" => Some("\u{2193}"),
    b"Downarrow" => Some("\u{21D3}"),
    b"ETH" => Some("\u{D0}"),
    b"Eacute" => Some("\u{C9}"),
    b"Ecirc" => Some("\u{CA}"),
    b"Egrave" => Some("\u{C8}"),
    b"Element" => Some("\u{2208}"),
    b"Epsilon" => Some("\u{395}"),
    b"Eta" => Some("\u{397}"),
    b"Euml" => Some("\u{CB}"),
    b"Exists" => Some("\u{2203}"),
    b"ForAll" => Some("\u{2200}"),
    b"GT" => Some(">"),
    b"Gamma" => Some("\u{393}"),
    b"GreaterEqual" => Some("\u{2265}"),
    b"Hat" => Some("^"),
    b"Iacute" => Some("\u{CD}"),
    b"Icirc" => Some("\u{CE}"),
    b"Ifr" => Some("\u{2111}"),
    b"Igrave" => Some("\u{CC}"),
    b"Im" => Some("\u{2111}"),
    b"Implies" => Some("\u{21D2}"),
    b"Integral" => Some("\u{222B}"),
    b"Iota" => Some("\u{399}"),
    b"Iuml" => Some("\u{CF}"),
    b"Kappa" => Some("\u{39A}"),
    b"LT" => Some("<"),
    b"Lambda" => Some("\u{39B}"),
    b"LeftAngleBracket" => Some("\u{27E8}"),
    b"LeftArrow" => Some("\u{2190}"),
    b"LeftCeiling" => Some("\u{2308}"),
    b"LeftFloor" => Some("\u{230A}"),
    b"LeftRightArrow" => Some("\u{2194}"),
    b"Leftarrow" => Some("\u{21D0}"),
    b"Leftrightarrow" => Some("\u{21D4}"),
    b"Mu" => Some("\u{39C}"),
    b"NewLine" => Some("\u{A}"),
    b"NonBreakingSpace" => Some("\u{A0}"),
    b"NotElement" => Some("\u{2209}"),
    b"NotEqual" => Some("\u{2260}"),
    b"NotEqualTilde" => Some("\u{2242}\u{338}"),
    b"NotSubset" => Some("\u{2282}\u{20D2}"),
    b"Ntilde" => Some("\u{D1}"),
    b"Nu" => Some("\u{39D}"),
    b"OElig" => Some("\u{152}"),
    b"Oacute" => Some("\u{D3}"),
    b"Ocirc" => Some("\u{D4}"),
    b"Ograve" => Some("\u{D2}"),
    b"Omega" => Some("\u{3A9}"),
    b"Omicron" => Some("\u{39F}"),
    b"OpenCurlyDoubleQuote" => Some("\u{201C}"),
    b"OpenCurlyQuote" => Some("\u{2018}"),
    b"Oslash" => Some("\u{D8}"),
    b"Otilde" => Some("\u{D5}"),
    b"Ouml" => Some("\u{D6}"),
    b"OverBar" => Some("\u{203E}"),
    b"PartialD" => Some("\u{2202}"),
    b"Phi" => Some("\u{3A6}"),
    b"Pi" => Some("\u{3A0}"),
    b"PlusMinus" => Some("\u{B1}"),
    b"Prime" => Some("\u{2033}"),
    b"Product" => Some("\u{220F}"),
    b"Proportional" => Some("\u{221D}"),
    b"Psi" => Some("\u{3A8}"),
    b"QUOT" => Some("\""),
    b"REG" => Some("\u{AE}"),
    b"Re" => Some("\u{211C}"),
    b"ReverseElement" => Some("\u{220B}"),
    b"Rfr" => Some("\u{211C}"),
    b"Rho" => Some("\u{3A1}"),
    b"RightAngleBracket" => Some("\u{27E9}"),
    b"RightArrow" => Some("\u{2192}"),
    b"RightCeiling" => Some("\u{2309}"),
    b"RightFloor" => Some("\u{230B}"),
    b"Rightarrow" => Some("\u{21D2}"),
    b"Scaron" => Some("\u{160}"),
    b"ShortDownArrow" => Some("\u{2193}"),
    b"ShortLeftArrow" => Some("\u{2190}"),
    b"ShortRightArrow" => Some("\u{2192}"),
    b"ShortUpArrow" => Some("\u{2191}"),
    b"Sigma" => Some("\u{3A3}"),
    b"Sqrt" => Some("\u{221A}"),
    b"SubsetEqual" => Some("\u{2286}"),
    b"SuchThat" => Some("\u{220B}"),
    b"Sum" => Some("\u{2211}"),
    b"Superset" => Some("\u{2283}"),
    b"SupersetEqual" => Some("\u{2287}"),
    b"THORN" => Some("\u{DE}"),
    b"TRADE" => Some("\u{2122}"),
    b"Tab" => Some("\u{9}"),
    b"Tau" => Some("\u{3A4}"),
    b"Therefore" => Some("\u{2234}"),
    b"Theta" => Some("\u{398}"),
    b"ThickSpace" => Some("\u{205F}\u{200A}"),
    b"ThinSpace" => Some("\u{2009}"),
    b"Tilde" => Some("\u{223C}"),
    b"TildeFullEqual" => Some("\u{2245}"),
    b"TildeTilde" => Some("\u{2248}"),
    b"Uacute" => Some("\u{DA}"),
    b"Ucirc" => Some("\u{DB}"),
    b"Ugrave" => Some("\u{D9}"),
    b"UnderBar" => Some("_"),
    b"UpArrow" => Some("\u{2191}"),
    b"UpTee" => Some("\u{22A5}"),
    b"Uparrow" => Some("\u{21D1}"),
    b"Upsi" => Some("\u{3D2}"),
    b"Upsilon" => Some("\u{3A5}"),
    b"Uuml" => Some("\u{DC}"),
    b"VerticalLine" => Some("|"),
    b"Xi" => Some("\u{39E}"),
    b"Yacute" => Some("\u{DD}"),
    b"Yuml" => Some("\u{178}"),
    b"Zeta" => Some("\u{396}"),
    b"aacute" => Some("\u{E1}"),
    b"acirc" => Some("\u{E2}"),
    b"acute" => Some("\u{B4}"),
    b"aelig" => Some("\u{E6}"),
    b"agrave" => Some("\u{E0}"),
    b"alefsym" => Some("\u{2135}"),
    b"aleph" => Some("\u{2135}"),
    b"alpha" => Some("\u{3B1}"),
    b"amp" => Some("&"),
    b"and" => Some("\u{2227}"),
    b"ang" => Some("\u{2220}"),
    b"angle" => Some("\u{2220}"),
    b"angst" => Some("\u{C5}"),
    b"ap" => Some("\u{2248}"),
    b"apos" => Some("'"),
    b"approx" => Some("\u{2248}"),
    b"aring" => Some("\u{E5}"),
    b"ast" => Some("*"),
    b"asymp" => Some("\u{2248}"),
    b"atilde" => Some("\u{E3}"),
    b"auml" => Some("\u{E4}"),
    b"bdquo" => Some("\u{201E}"),
    b"beta" => Some("\u{3B2}"),
    b"bot" => Some("\u{22A5}"),
    b"bottom" => Some("\u{22A5}"),
    b"brvbar" => Some("\u{A6}"),
    b"bsol" => Some("\\"),
    b"bull" => Some("\u{2022}"),
    b"bullet" => Some("\u{2022}"),
    b"cap" => Some("\u{2229}"),
    b"ccedil" => Some("\u{E7}"),
    b"cedil" => Some("\u{B8}"),
    b"cent" => Some("\u{A2}"),
    b"centerdot" => Some("\u{B7}"),
    b"chi" => Some("\u{3C7}"),
    b"circ" => Some("\u{2C6}"),
    b"circledR" => Some("\u{AE}"),
    b"clubs" => Some("\u{2663}"),
    b"clubsuit" => Some("\u{2663}"),
    b"colon" => Some(":"),
    b"comma" => Some(","),
    b"commat" => Some("@"),
    b"cong" => Some("\u{2245}"),
    b"copy" => Some("\u{A9}"),
    b"crarr" => Some("\u{21B5}"),
    b"cup" => Some("\u{222A}"),
    b"curren" => Some("\u{A4}"),
    b"dArr" => Some("\u{21D3}"),
    b"dagger" => Some("\u{2020}"),
    b"darr" => Some("\u{2193}"),
    b"ddagger" => Some("\u{2021}"),
    b"deg" => Some("\u{B0}"),
    b"delta" => Some("\u{3B4}"),
    b"diamondsuit" => Some("\u{2666}"),
    b"diams" => Some("\u{2666}"),
    b"die" => Some("\u{A8}"),
    b"div" => Some("\u{F7}"),
    b"divide" => Some("\u{F7}"),
    b"dollar" => Some("$"),
    b"downarrow" => Some("\u{2193}"),
    b"eacute" => Some("\u{E9}"),
    b"ecirc" => Some("\u{EA}"),
    b"egrave" => Some("\u{E8}"),
    b"empty" => Some("\u{2205}"),
    b"emptyset" => Some("\u{2205}"),
    b"emptyv" => Some("\u{2205}"),
    b"emsp" => Some("\u{2003}"),
    b"ensp" => Some("\u{2002}"),
    b"epsi" => Some("\u{3B5}"),
    b"epsilon" => Some("\u{3B5}"),
    b"equals" => Some("="),
    b"equiv" => Some("\u{2261}"),
    b"eta" => Some("\u{3B7}"),
    b"eth" => Some("\u{F0}"),
    b"euml" => Some("\u{EB}"),
    b"euro" => Some("\u{20AC}"),
    b"excl" => Some("!"),
    b"exist" => Some("\u{2203}"),
    b"fjlig" => Some("fj"),
    b"fnof" => Some("\u{192}"),
    b"forall" => Some("\u{2200}"),
    b"frac12" => Some("\u{BD}"),
    b"frac14" => Some("\u{BC}"),
    b"frac34" => Some("\u{BE}"),
    b"frasl" => Some("\u{2044}"),
    b"gamma" => Some("\u{3B3}"),
    b"ge" => Some("\u{2265}"),
    b"geq" => Some("\u{2265}"),
    b"grave" => Some("`"),
    b"gt" => Some(">"),
    b"hArr" => Some("\u{21D4}"),
    b"half" => Some("\u{BD}"),
    b"harr" => Some("\u{2194}"),
    b"hearts" => Some("\u{2665}"),
    b"heartsuit" => Some("\u{2665}"),
    b"hellip" => Some("\u{2026}"),
    b"iacute" => Some("\u{ED}"),
    b"icirc" => Some("\u{EE}"),
    b"iexcl" => Some("\u{A1}"),
    b"iff" => Some("\u{21D4}"),
    b"igrave" => Some("\u{EC}"),
    b"image" => Some("\u{2111}"),
    b"imagpart" => Some("\u{2111}"),
    b"in" => Some("\u{2208}"),
    b"infin" => Some("\u{221E}"),
    b"int" => Some("\u{222B}"),
    b"iota" => Some("\u{3B9}"),
    b"iquest" => Some("\u{BF}"),
    b"isin" => Some("\u{2208}"),
    b"isinv" => Some("\u{2208}"),
    b"iuml" => Some("\u{EF}"),
    b"kappa" => Some("\u{3BA}"),
    b"lArr" => Some("\u{21D0}"),
    b"lambda" => Some("\u{3BB}"),
    b"lang" => Some("\u{27E8}"),
    b"langle" => Some("\u{27E8}"),
    b"laquo" => Some("\u{AB}"),
    b"larr" => Some("\u{2190}"),
    b"lbrace" => Some("{"),
    b"lbrack" => Some("["),
    b"lceil" => Some("\u{2308}"),
    b"lcub" => Some("{"),
    b"ldquo" => Some("\u{201C}"),
    b"ldquor" => Some("\u{201E}"),
    b"le" => Some("\u{2264}"),
    b"leftarrow" => Some("\u{2190}"),
    b"leftrightarrow" => Some("\u{2194}"),
    b"leq" => Some("\u{2264}"),
    b"lfloor" => Some("\u{230A}"),
    b"lowast" => Some("\u{2217}"),
    b"lowbar" => Some("_"),
    b"loz" => Some("\u{25CA}"),
    b"lozenge" => Some("\u{25CA}"),
    b"lpar" => Some("("),
    b"lrm" => Some("\u{200E}"),
    b"lsaquo" => Some("\u{2039}"),
    b"lsqb" => Some("["),
    b"lsquo" => Some("\u{2018}"),
    b"lsquor" => Some("\u{201A}"),
    b"lt" => Some("<"),
    b"macr" => Some("\u{AF}"),
    b"mdash" => Some("\u{2014}"),
    b"micro" => Some("\u{B5}"),
    b"midast" => Some("*"),
    b"middot" => Some("\u{B7}"),
    b"minus" => Some("\u{2212}"),
    b"mldr" => Some("\u{2026}"),
    b"mu" => Some("\u{3BC}"),
    b"nabla" => Some("\u{2207}"),
    b"nbsp" => Some("\u{A0}"),
    b"ndash" => Some("\u{2013}"),
    b"ne" => Some("\u{2260}"),
    b"ni" => Some("\u{220B}"),
    b"niv" => Some("\u{220B}"),
    b"not" => Some("\u{AC}"),
    b"notin" => Some("\u{2209}"),
    b"notinva" => Some("\u{2209}"),
    b"nsub" => Some("\u{2284}"),
    b"ntilde" => Some("\u{F1}"),
    b"nu" => Some("\u{3BD}"),
    b"num" => Some("#"),
    b"oacute" => Some("\u{F3}"),
    b"ocirc" => Some("\u{F4}"),
    b"oelig" => Some("\u{153}"),
    b"ograve" => Some("\u{F2}"),
    b"ohm" => Some("\u{3A9}"),
    b"oline" => Some("\u{203E}"),
    b"omega" => Some("\u{3C9}"),
    b"omicron" => Some("\u{3BF}"),
    b"oplus" => Some("\u{2295}"),
    b"or" => Some("\u{2228}"),
    b"ordf" => Some("\u{AA}"),
    b"ordm" => Some("\u{BA}"),
    b"oslash" => Some("\u{F8}"),
    b"otilde" => Some("\u{F5}"),
    b"otimes" => Some("\u{2297}"),
    b"ouml" => Some("\u{F6}"),
    b"para" => Some("\u{B6}"),
    b"part" => Some("\u{2202}"),
    b"percnt" => Some("%"),
    b"period" => Some("."),
    b"permil" => Some("\u{2030}"),
    b"perp" => Some("\u{22A5}"),
    b"phi" => Some("\u{3C6}"),
    b"pi" => Some("\u{3C0}"),
    b"piv" => Some("\u{3D6}"),
    b"plus" => Some("+"),
    b"plusmn" => Some("\u{B1}"),
    b"pm" => Some("\u{B1}"),
    b"pound" => Some("\u{A3}"),
    b"prime" => Some("\u{2032}"),
    b"prod" => Some("\u{220F}"),
    b"prop" => Some("\u{221D}"),
    b"propto" => Some("\u{221D}"),
    b"psi" => Some("\u{3C8}"),
    b"quest" => Some("?"),
    b"quot" => Some("\""),
    b"rArr" => Some("\u{21D2}"),
    b"radic" => Some("\u{221A}"),
    b"rang" => Some("\u{27E9}"),
    b"rangle" => Some("\u{27E9}"),
    b"raquo" => Some("\u{BB}"),
    b"rarr" => Some("\u{2192}"),
    b"rbrace" => Some("}"),
    b"rbrack" => Some("]"),
    b"rceil" => Some("\u{2309}"),
    b"rcub" => Some("}"),
    b"rdquo" => Some("\u{201D}"),
    b"rdquor" => Some("\u{201D}"),
    b"real" => Some("\u{211C}"),
    b"realpart" => Some("\u{211C}"),
    b"reg" => Some("\u{AE}"),
    b"rfloor" => Some("\u{230B}"),
    b"rho" => Some("\u{3C1}"),
    b"rightarrow" => Some("\u{2192}"),
    b"rlm" => Some("\u{200F}"),
    b"rpar" => Some(")"),
    b"rsaquo" => Some("\u{203A}"),
    b"rsqb" => Some("]"),
    b"rsquo" => Some("\u{2019}"),
    b"rsquor" => Some("\u{2019}"),
    b"sbquo" => Some("\u{201A}"),
    b"scaron" => Some("\u{161}"),
    b"sdot" => Some("\u{22C5}"),
    b"sect" => Some("\u{A7}"),
    b"semi" => Some(";"),
    b"shy" => Some("\u{AD}"),
    b"sigma" => Some("\u{3C3}"),
    b"sigmaf" => Some("\u{3C2}"),
    b"sigmav" => Some("\u{3C2}"),
    b"sim" => Some("\u{223C}"),
    b"slarr" => Some("\u{2190}"),
    b"sol" => Some("/"),
    b"spades" => Some("\u{2660}"),
    b"spadesuit" => Some("\u{2660}"),
    b"srarr" => Some("\u{2192}"),
    b"strns" => Some("\u{AF}"),
    b"sub" => Some("\u{2282}"),
    b"sube" => Some("\u{2286}"),
    b"subset" => Some("\u{2282}"),
    b"subseteq" => Some("\u{2286}"),
    b"sum" => Some("\u{2211}"),
    b"sup" => Some("\u{2283}"),
    b"sup1" => Some("\u{B9}"),
    b"sup2" => Some("\u{B2}"),
    b"sup3" => Some("\u{B3}"),
    b"supe" => Some("\u{2287}"),
    b"supset" => Some("\u{2283}"),
    b"supseteq" => Some("\u{2287}"),
    b"szlig" => Some("\u{DF}"),
    b"tau" => Some("\u{3C4}"),
    b"there4" => Some("\u{2234}"),
    b"therefore" => Some("\u{2234}"),
    b"theta" => Some("\u{3B8}"),
    b"thetasym" => Some("\u{3D1}"),
    b"thetav" => Some("\u{3D1}"),
    b"thickapprox" => Some("\u{2248}"),
    b"thicksim" => Some("\u{223C}"),
    b"thinsp" => Some("\u{2009}"),
    b"thkap" => Some("\u{2248}"),
    b"thksim" => Some("\u{223C}"),
    b"thorn" => Some("\u{FE}"),
    b"tilde" => Some("\u{2DC}"),
    b"times" => Some("\u{D7}"),
    b"trade" => Some("\u{2122}"),
    b"uArr" => Some("\u{21D1}"),
    b"uacute" => Some("\u{FA}"),
    b"uarr" => Some("\u{2191}"),
    b"ucirc" => Some("\u{FB}"),
    b"ugrave" => Some("\u{F9}"),
    b"uml" => Some("\u{A8}"),
    b"uparrow" => Some("\u{2191}"),
    b"upsi" => Some("\u{3C5}"),
    b"upsih" => Some("\u{3D2}"),
    b"upsilon" => Some("\u{3C5}"),
    b"uuml" => Some("\u{FC}"),
    b"varnothing" => Some("\u{2205}"),
    b"varpi" => Some("\u{3D6}"),
    b"varpropto" => Some("\u{221D}"),
    b"varsigma" => Some("\u{3C2}"),
    b"vartheta" => Some("\u{3D1}"),
    b"vee" => Some("\u{2228}"),
    b"verbar" => Some("|"),
    b"vert" => Some("|"),
    b"vprop" => Some("\u{221D}"),
    b"wedge" => Some("\u{2227}"),
    b"weierp" => Some("\u{2118}"),
    b"wp" => Some("\u{2118}"),
    b"xi" => Some("\u{3BE}"),
    b"yacute" => Some("\u{FD}"),
    b"yen" => Some("\u{A5}"),
    b"yuml" => Some("\u{FF}"),
    b"zeta" => Some("\u{3B6}"),
    b"zwj" => Some("\u{200D}"),
    b"zwnj" => Some("\u{200C}"),
    _ => None,
  }
}

#[rustfmt::skip]
#[inline]
pub(super) fn is_legacy_named_entity(name: &[u8]) -> bool {
  matches!(name,
    b"AElig" |
    b"AMP" |
    b"Aacute" |
    b"Acirc" |
    b"Agrave" |
    b"Aring" |
    b"Atilde" |
    b"Auml" |
    b"COPY" |
    b"Ccedil" |
    b"ETH" |
    b"Eacute" |
    b"Ecirc" |
    b"Egrave" |
    b"Euml" |
    b"GT" |
    b"Iacute" |
    b"Icirc" |
    b"Igrave" |
    b"Iuml" |
    b"LT" |
    b"Ntilde" |
    b"Oacute" |
    b"Ocirc" |
    b"Ograve" |
    b"Oslash" |
    b"Otilde" |
    b"Ouml" |
    b"QUOT" |
    b"REG" |
    b"THORN" |
    b"Uacute" |
    b"Ucirc" |
    b"Ugrave" |
    b"Uuml" |
    b"Yacute" |
    b"aacute" |
    b"acirc" |
    b"acute" |
    b"aelig" |
    b"agrave" |
    b"amp" |
    b"aring" |
    b"atilde" |
    b"auml" |
    b"brvbar" |
    b"ccedil" |
    b"cedil" |
    b"cent" |
    b"copy" |
    b"curren" |
    b"deg" |
    b"divide" |
    b"eacute" |
    b"ecirc" |
    b"egrave" |
    b"eth" |
    b"euml" |
    b"frac12" |
    b"frac14" |
    b"frac34" |
    b"gt" |
    b"iacute" |
    b"icirc" |
    b"iexcl" |
    b"igrave" |
    b"iquest" |
    b"iuml" |
    b"laquo" |
    b"lt" |
    b"macr" |
    b"micro" |
    b"middot" |
    b"nbsp" |
    b"not" |
    b"ntilde" |
    b"oacute" |
    b"ocirc" |
    b"ograve" |
    b"ordf" |
    b"ordm" |
    b"oslash" |
    b"otilde" |
    b"ouml" |
    b"para" |
    b"plusmn" |
    b"pound" |
    b"quot" |
    b"raquo" |
    b"reg" |
    b"sect" |
    b"shy" |
    b"sup1" |
    b"sup2" |
    b"sup3" |
    b"szlig" |
    b"thorn" |
    b"times" |
    b"uacute" |
    b"ucirc" |
    b"ugrave" |
    b"uml" |
    b"uuml" |
    b"yacute" |
    b"yen" |
    b"yuml"
  )
}
