// Generated by scripts/generate-html-entities.mjs from the WHATWG table.
// Keep this file in parity with packages/js/src/entities.ts.

pub(super) const MAX_ENTITY_NAME_LENGTH: usize = 31;
pub(super) const MAX_LEGACY_ENTITY_NAME_LENGTH: usize = 6;

#[inline]
pub(super) fn lookup_named_entity(name: &[u8]) -> Option<&'static str> {
  match name {
    b"AElig" => Some("Æ"),
    b"AMP" => Some("&"),
    b"Aacute" => Some("Á"),
    b"Acirc" => Some("Â"),
    b"Agrave" => Some("À"),
    b"Alpha" => Some("Α"),
    b"Aring" => Some("Å"),
    b"Atilde" => Some("Ã"),
    b"Auml" => Some("Ä"),
    b"Beta" => Some("Β"),
    b"COPY" => Some("©"),
    b"Ccedil" => Some("Ç"),
    b"Cedilla" => Some("¸"),
    b"CenterDot" => Some("·"),
    b"Chi" => Some("Χ"),
    b"CirclePlus" => Some("⊕"),
    b"CircleTimes" => Some("⊗"),
    b"CloseCurlyDoubleQuote" => Some("”"),
    b"CloseCurlyQuote" => Some("’"),
    b"Congruent" => Some("≡"),
    b"CounterClockwiseContourIntegral" => Some("∳"),
    b"Dagger" => Some("‡"),
    b"Del" => Some("∇"),
    b"Delta" => Some("Δ"),
    b"DiacriticalAcute" => Some("´"),
    b"DiacriticalGrave" => Some("`"),
    b"DiacriticalTilde" => Some("˜"),
    b"Dot" => Some("¨"),
    b"DoubleDot" => Some("¨"),
    b"DoubleDownArrow" => Some("⇓"),
    b"DoubleLeftArrow" => Some("⇐"),
    b"DoubleLeftRightArrow" => Some("⇔"),
    b"DoubleRightArrow" => Some("⇒"),
    b"DoubleUpArrow" => Some("⇑"),
    b"DownArrow" => Some("↓"),
    b"Downarrow" => Some("⇓"),
    b"ETH" => Some("Ð"),
    b"Eacute" => Some("É"),
    b"Ecirc" => Some("Ê"),
    b"Egrave" => Some("È"),
    b"Element" => Some("∈"),
    b"Epsilon" => Some("Ε"),
    b"Eta" => Some("Η"),
    b"Euml" => Some("Ë"),
    b"Exists" => Some("∃"),
    b"ForAll" => Some("∀"),
    b"GT" => Some(">"),
    b"Gamma" => Some("Γ"),
    b"GreaterEqual" => Some("≥"),
    b"Hat" => Some("^"),
    b"Iacute" => Some("Í"),
    b"Icirc" => Some("Î"),
    b"Ifr" => Some("ℑ"),
    b"Igrave" => Some("Ì"),
    b"Im" => Some("ℑ"),
    b"Implies" => Some("⇒"),
    b"Integral" => Some("∫"),
    b"Iota" => Some("Ι"),
    b"Iuml" => Some("Ï"),
    b"Kappa" => Some("Κ"),
    b"LT" => Some("<"),
    b"Lambda" => Some("Λ"),
    b"LeftAngleBracket" => Some("⟨"),
    b"LeftArrow" => Some("←"),
    b"LeftCeiling" => Some("⌈"),
    b"LeftFloor" => Some("⌊"),
    b"LeftRightArrow" => Some("↔"),
    b"Leftarrow" => Some("⇐"),
    b"Leftrightarrow" => Some("⇔"),
    b"Mu" => Some("Μ"),
    b"NewLine" => Some("\n"),
    b"NonBreakingSpace" => Some(" "),
    b"NotElement" => Some("∉"),
    b"NotEqual" => Some("≠"),
    b"NotEqualTilde" => Some("≂̸"),
    b"NotSubset" => Some("⊂⃒"),
    b"Ntilde" => Some("Ñ"),
    b"Nu" => Some("Ν"),
    b"OElig" => Some("Œ"),
    b"Oacute" => Some("Ó"),
    b"Ocirc" => Some("Ô"),
    b"Ograve" => Some("Ò"),
    b"Omega" => Some("Ω"),
    b"Omicron" => Some("Ο"),
    b"OpenCurlyDoubleQuote" => Some("“"),
    b"OpenCurlyQuote" => Some("‘"),
    b"Oslash" => Some("Ø"),
    b"Otilde" => Some("Õ"),
    b"Ouml" => Some("Ö"),
    b"OverBar" => Some("‾"),
    b"PartialD" => Some("∂"),
    b"Phi" => Some("Φ"),
    b"Pi" => Some("Π"),
    b"PlusMinus" => Some("±"),
    b"Prime" => Some("″"),
    b"Product" => Some("∏"),
    b"Proportional" => Some("∝"),
    b"Psi" => Some("Ψ"),
    b"QUOT" => Some("\""),
    b"REG" => Some("®"),
    b"Re" => Some("ℜ"),
    b"ReverseElement" => Some("∋"),
    b"Rfr" => Some("ℜ"),
    b"Rho" => Some("Ρ"),
    b"RightAngleBracket" => Some("⟩"),
    b"RightArrow" => Some("→"),
    b"RightCeiling" => Some("⌉"),
    b"RightFloor" => Some("⌋"),
    b"Rightarrow" => Some("⇒"),
    b"Scaron" => Some("Š"),
    b"ShortDownArrow" => Some("↓"),
    b"ShortLeftArrow" => Some("←"),
    b"ShortRightArrow" => Some("→"),
    b"ShortUpArrow" => Some("↑"),
    b"Sigma" => Some("Σ"),
    b"Sqrt" => Some("√"),
    b"SubsetEqual" => Some("⊆"),
    b"SuchThat" => Some("∋"),
    b"Sum" => Some("∑"),
    b"Superset" => Some("⊃"),
    b"SupersetEqual" => Some("⊇"),
    b"THORN" => Some("Þ"),
    b"TRADE" => Some("™"),
    b"Tab" => Some("\t"),
    b"Tau" => Some("Τ"),
    b"Therefore" => Some("∴"),
    b"Theta" => Some("Θ"),
    b"ThickSpace" => Some("  "),
    b"ThinSpace" => Some(" "),
    b"Tilde" => Some("∼"),
    b"TildeFullEqual" => Some("≅"),
    b"TildeTilde" => Some("≈"),
    b"Uacute" => Some("Ú"),
    b"Ucirc" => Some("Û"),
    b"Ugrave" => Some("Ù"),
    b"UnderBar" => Some("_"),
    b"UpArrow" => Some("↑"),
    b"UpTee" => Some("⊥"),
    b"Uparrow" => Some("⇑"),
    b"Upsi" => Some("ϒ"),
    b"Upsilon" => Some("Υ"),
    b"Uuml" => Some("Ü"),
    b"VerticalLine" => Some("|"),
    b"Xi" => Some("Ξ"),
    b"Yacute" => Some("Ý"),
    b"Yuml" => Some("Ÿ"),
    b"Zeta" => Some("Ζ"),
    b"aacute" => Some("á"),
    b"acirc" => Some("â"),
    b"acute" => Some("´"),
    b"aelig" => Some("æ"),
    b"agrave" => Some("à"),
    b"alefsym" => Some("ℵ"),
    b"aleph" => Some("ℵ"),
    b"alpha" => Some("α"),
    b"amp" => Some("&"),
    b"and" => Some("∧"),
    b"ang" => Some("∠"),
    b"angle" => Some("∠"),
    b"angst" => Some("Å"),
    b"ap" => Some("≈"),
    b"apos" => Some("'"),
    b"approx" => Some("≈"),
    b"aring" => Some("å"),
    b"ast" => Some("*"),
    b"asymp" => Some("≈"),
    b"atilde" => Some("ã"),
    b"auml" => Some("ä"),
    b"bdquo" => Some("„"),
    b"beta" => Some("β"),
    b"bot" => Some("⊥"),
    b"bottom" => Some("⊥"),
    b"brvbar" => Some("¦"),
    b"bsol" => Some("\\"),
    b"bull" => Some("•"),
    b"bullet" => Some("•"),
    b"cap" => Some("∩"),
    b"ccedil" => Some("ç"),
    b"cedil" => Some("¸"),
    b"cent" => Some("¢"),
    b"centerdot" => Some("·"),
    b"chi" => Some("χ"),
    b"circ" => Some("ˆ"),
    b"circledR" => Some("®"),
    b"clubs" => Some("♣"),
    b"clubsuit" => Some("♣"),
    b"colon" => Some(":"),
    b"comma" => Some(","),
    b"commat" => Some("@"),
    b"cong" => Some("≅"),
    b"copy" => Some("©"),
    b"crarr" => Some("↵"),
    b"cup" => Some("∪"),
    b"curren" => Some("¤"),
    b"dArr" => Some("⇓"),
    b"dagger" => Some("†"),
    b"darr" => Some("↓"),
    b"ddagger" => Some("‡"),
    b"deg" => Some("°"),
    b"delta" => Some("δ"),
    b"diamondsuit" => Some("♦"),
    b"diams" => Some("♦"),
    b"die" => Some("¨"),
    b"div" => Some("÷"),
    b"divide" => Some("÷"),
    b"dollar" => Some("$"),
    b"downarrow" => Some("↓"),
    b"eacute" => Some("é"),
    b"ecirc" => Some("ê"),
    b"egrave" => Some("è"),
    b"empty" => Some("∅"),
    b"emptyset" => Some("∅"),
    b"emptyv" => Some("∅"),
    b"emsp" => Some(" "),
    b"ensp" => Some(" "),
    b"epsi" => Some("ε"),
    b"epsilon" => Some("ε"),
    b"equals" => Some("="),
    b"equiv" => Some("≡"),
    b"eta" => Some("η"),
    b"eth" => Some("ð"),
    b"euml" => Some("ë"),
    b"euro" => Some("€"),
    b"excl" => Some("!"),
    b"exist" => Some("∃"),
    b"fjlig" => Some("fj"),
    b"fnof" => Some("ƒ"),
    b"forall" => Some("∀"),
    b"frac12" => Some("½"),
    b"frac14" => Some("¼"),
    b"frac34" => Some("¾"),
    b"frasl" => Some("⁄"),
    b"gamma" => Some("γ"),
    b"ge" => Some("≥"),
    b"geq" => Some("≥"),
    b"grave" => Some("`"),
    b"gt" => Some(">"),
    b"hArr" => Some("⇔"),
    b"half" => Some("½"),
    b"harr" => Some("↔"),
    b"hearts" => Some("♥"),
    b"heartsuit" => Some("♥"),
    b"hellip" => Some("…"),
    b"iacute" => Some("í"),
    b"icirc" => Some("î"),
    b"iexcl" => Some("¡"),
    b"iff" => Some("⇔"),
    b"igrave" => Some("ì"),
    b"image" => Some("ℑ"),
    b"imagpart" => Some("ℑ"),
    b"in" => Some("∈"),
    b"infin" => Some("∞"),
    b"int" => Some("∫"),
    b"iota" => Some("ι"),
    b"iquest" => Some("¿"),
    b"isin" => Some("∈"),
    b"isinv" => Some("∈"),
    b"iuml" => Some("ï"),
    b"kappa" => Some("κ"),
    b"lArr" => Some("⇐"),
    b"lambda" => Some("λ"),
    b"lang" => Some("⟨"),
    b"langle" => Some("⟨"),
    b"laquo" => Some("«"),
    b"larr" => Some("←"),
    b"lbrace" => Some("{"),
    b"lbrack" => Some("["),
    b"lceil" => Some("⌈"),
    b"lcub" => Some("{"),
    b"ldquo" => Some("“"),
    b"ldquor" => Some("„"),
    b"le" => Some("≤"),
    b"leftarrow" => Some("←"),
    b"leftrightarrow" => Some("↔"),
    b"leq" => Some("≤"),
    b"lfloor" => Some("⌊"),
    b"lowast" => Some("∗"),
    b"lowbar" => Some("_"),
    b"loz" => Some("◊"),
    b"lozenge" => Some("◊"),
    b"lpar" => Some("("),
    b"lrm" => Some("‎"),
    b"lsaquo" => Some("‹"),
    b"lsqb" => Some("["),
    b"lsquo" => Some("‘"),
    b"lsquor" => Some("‚"),
    b"lt" => Some("<"),
    b"macr" => Some("¯"),
    b"mdash" => Some("—"),
    b"micro" => Some("µ"),
    b"midast" => Some("*"),
    b"middot" => Some("·"),
    b"minus" => Some("−"),
    b"mldr" => Some("…"),
    b"mu" => Some("μ"),
    b"nabla" => Some("∇"),
    b"nbsp" => Some(" "),
    b"ndash" => Some("–"),
    b"ne" => Some("≠"),
    b"ni" => Some("∋"),
    b"niv" => Some("∋"),
    b"not" => Some("¬"),
    b"notin" => Some("∉"),
    b"notinva" => Some("∉"),
    b"nsub" => Some("⊄"),
    b"ntilde" => Some("ñ"),
    b"nu" => Some("ν"),
    b"num" => Some("#"),
    b"oacute" => Some("ó"),
    b"ocirc" => Some("ô"),
    b"oelig" => Some("œ"),
    b"ograve" => Some("ò"),
    b"ohm" => Some("Ω"),
    b"oline" => Some("‾"),
    b"omega" => Some("ω"),
    b"omicron" => Some("ο"),
    b"oplus" => Some("⊕"),
    b"or" => Some("∨"),
    b"ordf" => Some("ª"),
    b"ordm" => Some("º"),
    b"oslash" => Some("ø"),
    b"otilde" => Some("õ"),
    b"otimes" => Some("⊗"),
    b"ouml" => Some("ö"),
    b"para" => Some("¶"),
    b"part" => Some("∂"),
    b"percnt" => Some("%"),
    b"period" => Some("."),
    b"permil" => Some("‰"),
    b"perp" => Some("⊥"),
    b"phi" => Some("φ"),
    b"pi" => Some("π"),
    b"piv" => Some("ϖ"),
    b"plus" => Some("+"),
    b"plusmn" => Some("±"),
    b"pm" => Some("±"),
    b"pound" => Some("£"),
    b"prime" => Some("′"),
    b"prod" => Some("∏"),
    b"prop" => Some("∝"),
    b"propto" => Some("∝"),
    b"psi" => Some("ψ"),
    b"quest" => Some("?"),
    b"quot" => Some("\""),
    b"rArr" => Some("⇒"),
    b"radic" => Some("√"),
    b"rang" => Some("⟩"),
    b"rangle" => Some("⟩"),
    b"raquo" => Some("»"),
    b"rarr" => Some("→"),
    b"rbrace" => Some("}"),
    b"rbrack" => Some("]"),
    b"rceil" => Some("⌉"),
    b"rcub" => Some("}"),
    b"rdquo" => Some("”"),
    b"rdquor" => Some("”"),
    b"real" => Some("ℜ"),
    b"realpart" => Some("ℜ"),
    b"reg" => Some("®"),
    b"rfloor" => Some("⌋"),
    b"rho" => Some("ρ"),
    b"rightarrow" => Some("→"),
    b"rlm" => Some("‏"),
    b"rpar" => Some(")"),
    b"rsaquo" => Some("›"),
    b"rsqb" => Some("]"),
    b"rsquo" => Some("’"),
    b"rsquor" => Some("’"),
    b"sbquo" => Some("‚"),
    b"scaron" => Some("š"),
    b"sdot" => Some("⋅"),
    b"sect" => Some("§"),
    b"semi" => Some(";"),
    b"shy" => Some("­"),
    b"sigma" => Some("σ"),
    b"sigmaf" => Some("ς"),
    b"sigmav" => Some("ς"),
    b"sim" => Some("∼"),
    b"slarr" => Some("←"),
    b"sol" => Some("/"),
    b"spades" => Some("♠"),
    b"spadesuit" => Some("♠"),
    b"srarr" => Some("→"),
    b"strns" => Some("¯"),
    b"sub" => Some("⊂"),
    b"sube" => Some("⊆"),
    b"subset" => Some("⊂"),
    b"subseteq" => Some("⊆"),
    b"sum" => Some("∑"),
    b"sup" => Some("⊃"),
    b"sup1" => Some("¹"),
    b"sup2" => Some("²"),
    b"sup3" => Some("³"),
    b"supe" => Some("⊇"),
    b"supset" => Some("⊃"),
    b"supseteq" => Some("⊇"),
    b"szlig" => Some("ß"),
    b"tau" => Some("τ"),
    b"there4" => Some("∴"),
    b"therefore" => Some("∴"),
    b"theta" => Some("θ"),
    b"thetasym" => Some("ϑ"),
    b"thetav" => Some("ϑ"),
    b"thickapprox" => Some("≈"),
    b"thicksim" => Some("∼"),
    b"thinsp" => Some(" "),
    b"thkap" => Some("≈"),
    b"thksim" => Some("∼"),
    b"thorn" => Some("þ"),
    b"tilde" => Some("˜"),
    b"times" => Some("×"),
    b"trade" => Some("™"),
    b"uArr" => Some("⇑"),
    b"uacute" => Some("ú"),
    b"uarr" => Some("↑"),
    b"ucirc" => Some("û"),
    b"ugrave" => Some("ù"),
    b"uml" => Some("¨"),
    b"uparrow" => Some("↑"),
    b"upsi" => Some("υ"),
    b"upsih" => Some("ϒ"),
    b"upsilon" => Some("υ"),
    b"uuml" => Some("ü"),
    b"varnothing" => Some("∅"),
    b"varpi" => Some("ϖ"),
    b"varpropto" => Some("∝"),
    b"varsigma" => Some("ς"),
    b"vartheta" => Some("ϑ"),
    b"vee" => Some("∨"),
    b"verbar" => Some("|"),
    b"vert" => Some("|"),
    b"vprop" => Some("∝"),
    b"wedge" => Some("∧"),
    b"weierp" => Some("℘"),
    b"wp" => Some("℘"),
    b"xi" => Some("ξ"),
    b"yacute" => Some("ý"),
    b"yen" => Some("¥"),
    b"yuml" => Some("ÿ"),
    b"zeta" => Some("ζ"),
    b"zwj" => Some("‍"),
    b"zwnj" => Some("‌"),
    _ => None,
  }
}

#[rustfmt::skip]
#[inline]
pub(super) fn is_legacy_named_entity(name: &[u8]) -> bool {
  matches!(name,
    b"AElig" |
    b"AMP" |
    b"Aacute" |
    b"Acirc" |
    b"Agrave" |
    b"Aring" |
    b"Atilde" |
    b"Auml" |
    b"COPY" |
    b"Ccedil" |
    b"ETH" |
    b"Eacute" |
    b"Ecirc" |
    b"Egrave" |
    b"Euml" |
    b"GT" |
    b"Iacute" |
    b"Icirc" |
    b"Igrave" |
    b"Iuml" |
    b"LT" |
    b"Ntilde" |
    b"Oacute" |
    b"Ocirc" |
    b"Ograve" |
    b"Oslash" |
    b"Otilde" |
    b"Ouml" |
    b"QUOT" |
    b"REG" |
    b"THORN" |
    b"Uacute" |
    b"Ucirc" |
    b"Ugrave" |
    b"Uuml" |
    b"Yacute" |
    b"aacute" |
    b"acirc" |
    b"acute" |
    b"aelig" |
    b"agrave" |
    b"amp" |
    b"aring" |
    b"atilde" |
    b"auml" |
    b"brvbar" |
    b"ccedil" |
    b"cedil" |
    b"cent" |
    b"copy" |
    b"curren" |
    b"deg" |
    b"divide" |
    b"eacute" |
    b"ecirc" |
    b"egrave" |
    b"eth" |
    b"euml" |
    b"frac12" |
    b"frac14" |
    b"frac34" |
    b"gt" |
    b"iacute" |
    b"icirc" |
    b"iexcl" |
    b"igrave" |
    b"iquest" |
    b"iuml" |
    b"laquo" |
    b"lt" |
    b"macr" |
    b"micro" |
    b"middot" |
    b"nbsp" |
    b"not" |
    b"ntilde" |
    b"oacute" |
    b"ocirc" |
    b"ograve" |
    b"ordf" |
    b"ordm" |
    b"oslash" |
    b"otilde" |
    b"ouml" |
    b"para" |
    b"plusmn" |
    b"pound" |
    b"quot" |
    b"raquo" |
    b"reg" |
    b"sect" |
    b"shy" |
    b"sup1" |
    b"sup2" |
    b"sup3" |
    b"szlig" |
    b"thorn" |
    b"times" |
    b"uacute" |
    b"ucirc" |
    b"ugrave" |
    b"uml" |
    b"uuml" |
    b"yacute" |
    b"yen" |
    b"yuml"
  )
}
